const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
let state={players:JSON.parse(localStorage.getItem('ghfc_players')||'null')||[],view:'dashboard'};
const save=()=>localStorage.setItem('ghfc_players',JSON.stringify(state.players));
const icon=n=>'<i data-lucide="'+n+'"></i>';
const labels={dashboard:'Resumen',players:'Deportistas',attendance:'Asistencia',training:'Entrenamientos',team:'Equipo y categorías',access:'Accesos',payments:'Pagos y cartera',activity:'Actividad'};
function categories(){return [...new Set(state.players.map(p=>p.category).filter(Boolean))]}
function placeholder(e,h,p){return '<div class="view"><div class="hero"><div><span class="eyebrow">'+e+'</span><h1>'+h+'</h1><p>'+p+'</p></div></div><div class="card empty">Módulo preparado para la siguiente fase.</div></div>'}
function playersTable(rows){if(!rows.length)return '<div class="empty">Aún no hay deportistas registrados.</div>';return '<div class="table-wrap"><table class="table players-table"><thead><tr><th>DEPORTISTA</th><th>CATEGORÍA</th><th>ACUDIENTE</th><th>CELULAR</th><th></th></tr></thead><tbody>'+rows.map(p=>'<tr><td><span class="player-name">'+p.name+'</span></td><td>'+(p.category||'—')+'</td><td>'+(p.guardian||'—')+'</td><td>'+(p.phone||'—')+'</td><td><button class="link-btn" data-player="'+p.id+'">Ver ficha</button></td></tr>').join('')+'</tbody></table></div>'}
function dashboard(){return '<div class="view"><div class="hero"><div><span class="eyebrow">BASE DEL CLUB</span><h1>Tu club, conectado.</h1><p>Las fichas y la asistencia se guardan en la base compartida.</p></div><button class="primary" data-open-player>'+icon('plus')+' Registrar deportista</button></div><div class="stats"><div class="stat"><div class="stat-top"><div class="stat-label">Deportistas registrados</div><div class="stat-icon">'+icon('users')+'</div></div><div class="stat-value">'+state.players.length+'</div><div class="stat-sub">Sin registros ficticios</div></div><div class="stat"><div class="stat-top"><div class="stat-label">Categorías</div><div class="stat-icon">'+icon('circle-dot')+'</div></div><div class="stat-value">'+(categories().length||7)+'</div><div class="stat-sub">Con horarios configurados</div></div><div class="stat"><div class="stat-top"><div class="stat-label">Sesiones de la semana</div><div class="stat-icon">'+icon('calendar-days')+'</div></div><div class="stat-value">21</div><div class="stat-sub">Según el horario habitual</div></div><div class="stat"><div class="stat-top"><div class="stat-label">Acceso</div><div class="stat-icon">'+icon('clipboard-check')+'</div></div><div class="stat-value word">Administrativo</div><div class="stat-sub">Felipe Abril</div></div></div><div class="grid-2"><div class="card"><div class="card-head"><h3>Para comenzar</h3></div><div class="quick-row"><div class="quick-icon">'+icon('users-round')+'</div><div class="quick-copy"><strong>Fichas de deportistas</strong><span>Acudiente, emergencias y seguimiento físico</span></div><button class="link-btn" data-view-link="players">Abrir</button></div><div class="quick-row"><div class="quick-icon">'+icon('clipboard-check')+'</div><div class="quick-copy"><strong>Asistencia por sesión</strong><span>Una lista compartida por los profesores asignados</span></div><button class="link-btn" data-view-link="attendance">Tomar lista</button></div><div class="quick-row"><div class="quick-icon">'+icon('calendar-days')+'</div><div class="quick-copy"><strong>Entrenamientos</strong><span>Horarios, categorías, escenarios y responsables</span></div><button class="link-btn" data-view-link="training">Ver agenda</button></div></div><div class="card"><div class="card-head"><h3>Esta primera etapa</h3></div><div class="info-copy">Ya puedes guardar fichas, editar sus datos, registrar mediciones y tomar asistencia.</div><div class="info-note">Pagos y cartera disponibles desde octubre de 2026. Primero revisa y activa cada cuenta; los archivos y el envío de correos siguen pendientes.</div></div></div></div>'}
function players(){return '<div class="view"><div class="hero"><div><span class="eyebrow">DEPORTISTAS</span><h1>Fichas de deportistas</h1><p>Consulta, registra y administra la información principal del club.</p></div><button class="primary" data-open-player>'+icon('plus')+' Registrar deportista</button></div><div class="card"><div class="card-head"><h3>Deportistas registrados</h3></div><div id="playersTable">'+playersTable(state.players)+'</div></div></div>'}
const views={dashboard,players,attendance:()=>placeholder('ASISTENCIA','Asistencia por sesión','Toma lista por entrenamiento y consulta el seguimiento de cada deportista.'),training:()=>placeholder('ENTRENAMIENTOS','Agenda deportiva','Horarios, categorías, escenarios y responsables.'),team:()=>placeholder('EQUIPO Y CATEGORÍAS','Equipo y categorías','Configura categorías, entrenadores y horarios.'),access:()=>placeholder('ACCESOS','Accesos del club','Administra quién puede ingresar y qué módulos puede utilizar.'),payments:()=>placeholder('PAGOS Y CARTERA','Pagos y cartera','Registra abonos, consulta saldos y genera comprobantes.'),activity:()=>placeholder('ACTIVIDAD','Actividad reciente','Consulta los movimientos recientes de la aplicación.')};
function render(){document.querySelector('#viewRoot').innerHTML=views[state.view]();$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));$('#breadcrumb').innerHTML='Mi club <span>/</span> <strong>'+labels[state.view]+'</strong>';bind();if(window.lucide)lucide.createIcons()}
function go(v){state.view=v;render();closeMenu()}
function bind(){$$('[data-view-link]').forEach(b=>b.onclick=()=>go(b.dataset.viewLink));$$('[data-open-player]').forEach(b=>b.onclick=()=>$('#playerCreateDialog').showModal());$$('[data-player]').forEach(b=>b.onclick=()=>showPlayer(b.dataset.player))}
$$('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.view));
$('#playerCreateForm').addEventListener('submit',e=>{e.preventDefault();state.players.push({id:Date.now(),name:$('#newPlayerName').value.trim(),category:$('#newPlayerCategory').value.trim(),birth:$('#newPlayerBirth').value,monthly:Number($('#newPlayerMonthly').value)||0,guardian:$('#newPlayerGuardian').value.trim(),phone:$('#newPlayerPhone').value.trim()});save();$('#playerCreateDialog').close();e.target.reset();render()});
function showPlayer(id){const p=state.players.find(x=>x.id===Number(id));if(!p)return;$('#playerDetail').innerHTML='<div class="dialog-head"><div><span class="eyebrow">FICHA DEPORTIVA</span><h2>'+p.name+'</h2></div><button class="close-btn" onclick="document.querySelector(\'#playerDialog\').close()">×</button></div><div class="detail-grid"><div class="detail-field"><span>Categoría</span><strong>'+(p.category||'—')+'</strong></div><div class="detail-field"><span>Fecha nacimiento</span><strong>'+(p.birth||'—')+'</strong></div><div class="detail-field"><span>Mensualidad</span><strong>$ '+Number(p.monthly||0).toLocaleString('es-CO')+'</strong></div><div class="detail-field"><span>Acudiente</span><strong>'+(p.guardian||'—')+'</strong></div><div class="detail-field"><span>Celular</span><strong>'+(p.phone||'—')+'</strong></div></div>';$('#playerDialog').showModal()}
const menuBtn=$('#menuBtn'),sidebar=$('#sidebar'),overlay=$('#overlay');menuBtn.onclick=()=>{sidebar.classList.toggle('open');overlay.classList.toggle('active')};overlay.onclick=closeMenu;function closeMenu(){sidebar.classList.remove('open');overlay.classList.remove('active')}
render();