const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const COP=new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0});
const today=new Date();
const seedPlayers=[
{id:1,name:'Tomás Soler',birth:'2017-02-14',category:'2016–2017',guardian:'Laura Soler',phone:'300 555 0111',monthly:50000,status:'Habilitado'},
{id:2,name:'Miguel Gutiérrez',birth:'2016-09-03',category:'2016–2017',guardian:'Carlos Gutiérrez',phone:'300 555 0112',monthly:50000,status:'Habilitado'},
{id:3,name:'Emily Solano',birth:'2017-01-21',category:'2016–2017',guardian:'Diana Solano',phone:'300 555 0113',monthly:50000,status:'Habilitado'},
{id:4,name:'Santiago Díaz',birth:'2016-06-17',category:'2016–2017',guardian:'Andrea Díaz',phone:'300 555 0114',monthly:50000,status:'Pendiente'},
{id:5,name:'Gabriel Rangel',birth:'2017-04-09',category:'2016–2017',guardian:'Mónica Rangel',phone:'300 555 0115',monthly:50000,status:'Habilitado'},
{id:6,name:'Samuel Márquez',birth:'2016-12-30',category:'2016–2017',guardian:'Jorge Márquez',phone:'300 555 0116',monthly:50000,status:'Pendiente'},
{id:7,name:'Juan Pablo Hernández',birth:'2012-05-12',category:'2012–2013',guardian:'Paola Hernández',phone:'300 555 0121',monthly:50000,status:'Habilitado'},
{id:8,name:'Felipe Tobos',birth:'2012-11-08',category:'2012–2013',guardian:'María Tobos',phone:'300 555 0122',monthly:50000,status:'Habilitado'},
{id:9,name:'Juan Pablo Ríos',birth:'2013-03-24',category:'2012–2013',guardian:'Sandra Ríos',phone:'300 555 0123',monthly:50000,status:'Habilitado'},
{id:10,name:'Ervin Rangel',birth:'2012-08-19',category:'2012–2013',guardian:'Henry Rangel',phone:'300 555 0124',monthly:50000,status:'Pendiente'},
{id:11,name:'Oscar Villamizar',birth:'2013-02-05',category:'2012–2013',guardian:'Claudia Villamizar',phone:'300 555 0125',monthly:50000,status:'Habilitado'},
{id:12,name:'Santiago Salazar',birth:'2012-10-18',category:'2012–2013',guardian:'Luis Salazar',phone:'300 555 0126',monthly:50000,status:'Pendiente'}];
const seedPayments=[
{id:1001,playerId:1,concept:'Mensualidad',month:'2026-09',amount:50000,method:'Efectivo',type:'Pago completo',date:'2026-09-28',note:''},
{id:1002,playerId:3,concept:'Mensualidad',month:'2026-09',amount:50000,method:'Transferencia',type:'Pago completo',date:'2026-09-27',note:''},
{id:1003,playerId:5,concept:'Mensualidad',month:'2026-09',amount:50000,method:'Efectivo',type:'Pago completo',date:'2026-09-26',note:''},
{id:1004,playerId:7,concept:'Mensualidad',month:'2026-09',amount:50000,method:'Transferencia',type:'Pago completo',date:'2026-09-24',note:''},
{id:1005,playerId:8,concept:'Mensualidad',month:'2026-09',amount:50000,method:'Efectivo',type:'Pago completo',date:'2026-09-22',note:''},
{id:1006,playerId:9,concept:'Mensualidad',month:'2026-09',amount:50000,method:'Nequi',type:'Pago completo',date:'2026-09-20',note:''},
{id:1007,playerId:11,concept:'Mensualidad',month:'2026-09',amount:50000,method:'Efectivo',type:'Pago completo',date:'2026-09-18',note:''},
{id:1008,playerId:2,concept:'Mensualidad',month:'2026-09',amount:25000,method:'Efectivo',type:'Abono',date:'2026-09-17',note:'Abono parcial'}];
const trainings=[
{day:'Martes',date:'29/09/2026',time:'19:00–20:30',category:'2016–2017',place:'Cancha de tierra Beraka',coach:'Mateo Rincón · Felipe Abril'},
{day:'Miércoles',date:'30/09/2026',time:'17:30–19:00',category:'2012–2013',place:'Cancha sintética La Prosperidad',coach:'Felipe Abril'},
{day:'Jueves',date:'01/10/2026',time:'19:00–20:30',category:'2016–2017',place:'Cancha sintética La Prosperidad',coach:'Mateo Rincón'}];
let state={players:JSON.parse(localStorage.getItem('ghfc_players')||'null')||seedPlayers,payments:JSON.parse(localStorage.getItem('ghfc_payments')||'null')||seedPayments,view:'dashboard'};
function persist(){localStorage.setItem('ghfc_players',JSON.stringify(state.players));localStorage.setItem('ghfc_payments',JSON.stringify(state.payments));}
function player(id){return state.players.find(p=>p.id===Number(id));}
function monthLabel(m){const [y,mo]=m.split('-');return new Date(Number(y),Number(mo)-1,1).toLocaleDateString('es-CO',{month:'long',year:'numeric'});}
function currentMonth(){return '2026-09';}
function paymentFor(pid,m=currentMonth()){return state.payments.filter(x=>x.playerId===pid&&x.concept==='Mensualidad'&&x.month===m).reduce((a,b)=>a+b.amount,0)}
function balanceFor(p,m=currentMonth()){return Math.max(0,p.monthly-paymentFor(p.id,m))}
function totalCollected(){return state.payments.filter(x=>x.month===currentMonth()).reduce((a,b)=>a+b.amount,0)}
function statusPill(p){const bal=balanceFor(p);return bal===0?'<span class="pill ok">Al día</span>':paymentFor(p.id)>0?'<span class="pill warn">Abono</span>':'<span class="pill off">Pendiente</span>'}
const views={
 dashboard(){const pending=state.players.filter(p=>balanceFor(p)>0);return `<div class="view"><div class="hero"><div><span class="eyebrow">PANEL ADMINISTRATIVO</span><h1>El club, en un solo lugar.</h1><p>Control básico de deportistas, cartera, pagos y entrenamientos.</p></div><button class="primary" data-open-payment>Registrar pago</button></div><div class="stats"><div class="stat"><div class="stat-label">Deportistas</div><div class="stat-value">${state.players.length}</div><div class="stat-sub">${new Set(state.players.map(p=>p.category)).size} categorías activas</div></div><div class="stat"><div class="stat-label">Recaudo de septiembre</div><div class="stat-value">${COP.format(totalCollected())}</div><div class="stat-sub">Pagos registrados</div></div><div class="stat"><div class="stat-label">Cartera pendiente</div><div class="stat-value">${COP.format(pending.reduce((a,p)=>a+balanceFor(p),0))}</div><div class="stat-sub">${pending.length} deportistas con saldo</div></div><div class="stat"><div class="stat-label">Al día</div><div class="stat-value">${state.players.filter(p=>balanceFor(p)===0).length} / ${state.players.length}</div><div class="stat-sub">Mensualidad de septiembre</div></div></div><div class="grid-2"><div class="card"><div class="card-head"><div><h3>Así se mueve el club</h3><span class="muted" style="font-size:11px">Visualización abril a septiembre</span></div><div class="legend"><span><i></i>Ingresos</span><span class="exp"><i></i>Gastos</span></div></div>${chart()}</div><div class="card"><div class="card-head"><h3>Para tener en cuenta</h3></div><div class="notice-list"><div class="notice"><strong>Mensualidades pendientes</strong><p>${pending.length} deportistas tienen saldo en septiembre.</p></div><div class="notice"><strong>Base de datos local</strong><p>Los cambios se guardan en este navegador hasta conectar Supabase.</p></div><div class="notice"><strong>Comprobantes</strong><p>Cada pago puede descargarse en PDF.</p></div></div></div></div><div class="grid-2"><div class="card"><div class="card-head"><h3>Últimos pagos</h3><button class="link-btn" data-view-link="payments">Ver todos</button></div>${paymentsTable(state.payments.slice().sort((a,b)=>b.id-a.id).slice(0,5))}</div><div class="card"><div class="card-head"><h3>Próximo entrenamiento</h3></div>${trainingCard(trainings[0])}</div></div></div>`},
 players(){return `<div class="view"><div class="hero"><div><span class="eyebrow">DEPORTISTAS</span><h1>Fichas de jugadores</h1><p>Consulta rápida, estado de mensualidad y datos del acudiente.</p></div></div><div class="card"><div class="card-head"><div class="search-row"><input id="playerSearch" placeholder="Buscar por nombre"><select id="catFilter"><option value="">Todas las categorías</option>${[...new Set(state.players.map(p=>p.category))].map(c=>`<option>${c}</option>`).join('')}</select></div></div><div id="playersTable">${playersTable(state.players)}</div></div></div>`},
 payments(){const pending=state.players.filter(p=>balanceFor(p)>0);return `<div class="view"><div class="hero"><div><span class="eyebrow">PAGOS Y CARTERA</span><h1>Movimientos financieros</h1><p>Mensualidades, abonos y comprobantes.</p></div><button class="primary" data-open-payment>Registrar pago</button></div><div class="stats"><div class="stat"><div class="stat-label">Recaudado</div><div class="stat-value">${COP.format(totalCollected())}</div><div class="stat-sub">Septiembre</div></div><div class="stat"><div class="stat-label">Pendiente</div><div class="stat-value">${COP.format(pending.reduce((a,p)=>a+balanceFor(p),0))}</div><div class="stat-sub">Cartera del mes</div></div><div class="stat"><div class="stat-label">Movimientos</div><div class="stat-value">${state.payments.length}</div><div class="stat-sub">Registros guardados</div></div><div class="stat"><div class="stat-label">Con abono</div><div class="stat-value">${state.players.filter(p=>paymentFor(p.id)>0&&balanceFor(p)>0).length}</div><div class="stat-sub">Pago parcial</div></div></div><div class="card" style="margin-top:16px"><div class="card-head"><h3>Historial de pagos</h3></div>${paymentsTable(state.payments.slice().sort((a,b)=>b.id-a.id),true)}</div></div>`},
 attendance(){return placeholder('ASISTENCIA','Control de asistencia','Aquí conectaremos listas por entrenamiento y porcentajes de asistencia por deportista.')},
 training(){return `<div class="view"><div class="hero"><div><span class="eyebrow">ENTRENAMIENTOS</span><h1>Agenda deportiva</h1><p>Horarios y escenarios previstos.</p></div></div><div class="card">${trainings.map(trainingCard).join('')}</div></div>`},
 team(){return placeholder('EQUIPO Y CATEGORÍAS','Estructura del club','En esta sección añadiremos entrenadores, categorías, tarifas y permisos de usuario.')}
};
function placeholder(e,h,p){return `<div class="view"><div class="hero"><div><span class="eyebrow">${e}</span><h1>${h}</h1><p>${p}</p></div></div><div class="card empty">Módulo preparado para la siguiente fase.</div></div>`}
function chart(){const inc=[280,310,340,325,365,375],exp=[205,220,215,245,230,255],labels=['Abr','May','Jun','Jul','Ago','Sep'];return `<div class="chart">${labels.map((l,i)=>`<div class="bar-group"><div class="bar" style="height:${inc[i]/4.2}px"></div><div class="bar expense" style="height:${exp[i]/4.2}px"></div><span>${l}</span></div>`).join('')}</div>`}
function trainingCard(t){return `<div class="training-card"><div><strong>${t.day} · ${t.date}</strong><span>${t.time} · ${t.category}<br>${t.place}<br>${t.coach}</span></div><button class="secondary compact" data-view-link="attendance">Tomar asistencia</button></div>`}
function playersTable(rows){return `<div class="table-wrap"><table class="table players-table"><thead><tr><th>DEPORTISTA</th><th>CATEGORÍA</th><th>ACUDIENTE</th><th>CELULAR</th><th>ESTADO</th><th></th></tr></thead><tbody>${rows.map(p=>`<tr><td><span class="player-name">${p.name}</span></td><td>${p.category}</td><td>${p.guardian}</td><td>${p.phone}</td><td>${statusPill(p)}</td><td><button class="link-btn" data-player="${p.id}">Ver ficha</button></td></tr>`).join('')}</tbody></table></div>`}
function paymentsTable(rows,actions=false){return `<div class="table-wrap"><table class="table"><thead><tr><th>DEPORTISTA</th><th>CONCEPTO</th><th>FECHA</th><th>MEDIO</th><th>VALOR</th>${actions?'<th></th>':''}</tr></thead><tbody>${rows.map(x=>{const p=player(x.playerId);return `<tr><td><span class="player-name">${p?.name||'—'}</span></td><td>${x.concept} · ${monthLabel(x.month)}</td><td>${x.date}</td><td>${x.method}</td><td><strong>${COP.format(x.amount)}</strong></td>${actions?`<td><button class="link-btn" data-receipt="${x.id}">PDF</button></td>`:''}</tr>`}).join('')}</tbody></table></div>`}
function render(){const root=$('#viewRoot');root.innerHTML=views[state.view]();$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));$('#breadcrumb').textContent='Mi club / '+({dashboard:'Resumen',players:'Deportistas',payments:'Pagos y cartera',attendance:'Asistencia',training:'Entrenamientos',team:'Equipo y categorías'}[state.view]);bindDynamic();}
function bindDynamic(){$$('[data-open-payment]').forEach(b=>b.onclick=openPayment);$$('[data-view-link]').forEach(b=>b.onclick=()=>go(b.dataset.viewLink));$$('[data-player]').forEach(b=>b.onclick=()=>showPlayer(b.dataset.player));$$('[data-receipt]').forEach(b=>b.onclick=()=>receipt(Number(b.dataset.receipt),true));const s=$('#playerSearch'),f=$('#catFilter');if(s){const filter=()=>{const q=s.value.toLowerCase(),cat=f.value;$('#playersTable').innerHTML=playersTable(state.players.filter(p=>p.name.toLowerCase().includes(q)&&(!cat||p.category===cat)));$$('[data-player]').forEach(b=>b.onclick=()=>showPlayer(b.dataset.player));};s.oninput=filter;f.onchange=filter;}}
function go(v){state.view=v;render();closeMenu();}
$$('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.view));
function openPayment(){const d=$('#paymentDialog');$('#paymentPlayer').innerHTML=state.players.map(p=>`<option value="${p.id}">${p.name} · ${p.category}</option>`).join('');$('#paymentMonth').value=currentMonth();$('#paymentAmount').value=50000;d.showModal();}
$('#paymentForm').addEventListener('submit',e=>{e.preventDefault();const x={id:Date.now(),playerId:Number($('#paymentPlayer').value),concept:$('#paymentConcept').value,month:$('#paymentMonth').value,amount:Number($('#paymentAmount').value),method:$('#paymentMethod').value,type:$('#paymentType').value,date:new Date().toISOString().slice(0,10),note:$('#paymentNote').value};state.payments.push(x);persist();$('#paymentDialog').close();render();receipt(x.id,true);});
function showPlayer(id){const p=player(id),bal=balanceFor(p);const recent=state.payments.filter(x=>x.playerId===p.id).sort((a,b)=>b.id-a.id);$('#playerDetail').innerHTML=`<div class="detail-top"><div><span class="eyebrow">FICHA DEPORTIVA</span><h2>${p.name}</h2><span class="pill ${bal===0?'ok':'warn'}">${bal===0?'Mensualidad al día':'Saldo '+COP.format(bal)}</span></div><button class="close-btn" onclick="document.querySelector('#playerDialog').close()">×</button></div><div class="detail-grid"><div class="detail-field"><span>Categoría</span><strong>${p.category}</strong></div><div class="detail-field"><span>Fecha nacimiento</span><strong>${p.birth}</strong></div><div class="detail-field"><span>Mensualidad</span><strong>${COP.format(p.monthly)}</strong></div><div class="detail-field"><span>Acudiente</span><strong>${p.guardian}</strong></div><div class="detail-field"><span>Celular</span><strong>${p.phone}</strong></div><div class="detail-field"><span>Estado</span><strong>${p.status}</strong></div></div><div class="card-head"><h3>Pagos recientes</h3><button class="primary compact" onclick="document.querySelector('#playerDialog').close();openPaymentFor(${p.id})">Registrar pago</button></div>${recent.length?paymentsTable(recent):'<div class="empty">Sin pagos registrados.</div>'}`;$('#playerDialog').showModal();}
window.openPaymentFor=id=>{openPayment();$('#paymentPlayer').value=id};
async function receipt(id,download=false){const x=state.payments.find(p=>p.id===id),p=player(x.playerId);if(!window.jspdf){alert('No se pudo cargar el generador PDF. Revisa la conexión a internet.');return}const {jsPDF}=window.jspdf;const doc=new jsPDF();doc.setFillColor(13,39,94);doc.rect(0,0,210,34,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(18);doc.text('GARCÍA HERREROS FÚTBOL CLUB',18,17);doc.setFontSize(9);doc.setFont('helvetica','normal');doc.text('COMPROBANTE DE PAGO',18,25);doc.setTextColor(35,45,65);doc.setFontSize(11);let y=50;const line=(a,b)=>{doc.setFont('helvetica','bold');doc.text(a,18,y);doc.setFont('helvetica','normal');doc.text(String(b),72,y);y+=10};line('Comprobante:',String(x.id));line('Fecha:',x.date);line('Deportista:',p.name);line('Categoría:',p.category);line('Concepto:',`${x.concept} - ${monthLabel(x.month)}`);line('Tipo:',x.type);line('Medio:',x.method);doc.setDrawColor(220,225,235);doc.line(18,y,192,y);y+=14;doc.setFontSize(16);doc.setFont('helvetica','bold');doc.text('VALOR RECIBIDO',18,y);doc.text(COP.format(x.amount),192,y,{align:'right'});y+=16;if(x.note){doc.setFontSize(10);doc.setFont('helvetica','normal');doc.text('Observación: '+x.note,18,y)}doc.setFontSize(8);doc.setTextColor(110,120,140);doc.text('Documento generado por el sistema administrativo del Club Deportivo García Herreros.',18,276);doc.text('Este comprobante corresponde al registro interno del pago informado.',18,282);if(download)doc.save(`Comprobante_${p.name.replaceAll(' ','_')}_${x.id}.pdf`);}
window.receipt=receipt;
const menuBtn=$('#menuBtn'),sidebar=$('#sidebar'),overlay=$('#overlay');menuBtn.onclick=()=>{sidebar.classList.toggle('open');overlay.classList.toggle('active')};overlay.onclick=closeMenu;function closeMenu(){sidebar.classList.remove('open');overlay.classList.remove('active')}
render();
