import { sqliteTable, text, integer, real, uniqueIndex, index } from 'drizzle-orm/sqlite-core';
export const staff = sqliteTable('staff', {
 id:text('id').primaryKey(),name:text('name').notNull(),title:text('title').notNull(),role:text('role').notNull(),coachId:text('coach_id'),email:text('email'),authId:text('auth_id'),active:integer('active').notNull().default(1),owner:integer('owner').notNull().default(0)
},t=>[uniqueIndex('staff_email_unique').on(t.email),uniqueIndex('staff_auth_unique').on(t.authId)]);
export const athletes = sqliteTable('athletes',{
 id:text('id').primaryKey(),name:text('name').notNull(),dob:text('dob').notNull(),category:text('category').notNull(),docType:text('doc_type'),docNumber:text('doc_number'),address:text('address'),guardian:text('guardian').notNull(),relationship:text('relationship').notNull(),phone:text('phone').notNull(),email:text('email'),emergencyName:text('emergency_name').notNull(),emergencyRelation:text('emergency_relation').notNull(),emergencyPhone:text('emergency_phone').notNull(),healthNotes:text('health_notes'),modality:text('modality').notNull(),consent:integer('consent').notNull(),consentDate:text('consent_date').notNull(),status:text('status').notNull().default('active'),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),version:integer('version').notNull().default(1)
},t=>[uniqueIndex('athletes_document_unique').on(t.docNumber),index('athletes_category_idx').on(t.category)]);
export const measurements = sqliteTable('measurements',{id:text('id').primaryKey(),athleteId:text('athlete_id').notNull().references(()=>athletes.id),date:text('date').notNull(),weight:real('weight').notNull(),height:real('height').notNull(),bmi:real('bmi').notNull(),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull()},t=>[index('measurements_athlete_idx').on(t.athleteId,t.date)]);
export const sessions = sqliteTable('sessions',{id:text('id').primaryKey(),date:text('date').notNull(),category:text('category').notNull(),notes:text('notes').notNull().default(''),status:text('status').notNull().default('programada'),attendanceJson:text('attendance_json').notNull().default('{}'),attendanceSaved:integer('attendance_saved').notNull().default(0),version:integer('version').notNull().default(1),updatedBy:text('updated_by').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('sessions_date_idx').on(t.date)]);
export const audit = sqliteTable('audit',{id:text('id').primaryKey(),actor:text('actor').notNull(),action:text('action').notNull(),entityId:text('entity_id').notNull(),createdAt:text('created_at').notNull()},t=>[index('audit_created_idx').on(t.createdAt)]);
export const billing = sqliteTable('billing',{
 athleteId:text('athlete_id').primaryKey().references(()=>athletes.id),startMonth:text('start_month').notNull(),annualStartYear:integer('annual_start_year').notNull(),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull()
});
export const charges = sqliteTable('charges',{
 id:text('id').primaryKey(),athleteId:text('athlete_id').notNull().references(()=>athletes.id),kind:text('kind').notNull(),period:text('period').notNull(),amount:integer('amount').notNull(),source:text('source').notNull(),notes:text('notes').notNull().default(''),status:text('status').notNull().default('active'),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull(),voidReason:text('void_reason'),voidBy:text('void_by'),voidAt:text('void_at')
},t=>[uniqueIndex('charges_athlete_period_unique').on(t.athleteId,t.kind,t.period),index('charges_athlete_idx').on(t.athleteId)]);
export const payments = sqliteTable('payments',{
 id:integer('id').primaryKey({autoIncrement:true}),requestId:text('request_id').notNull(),payload:text('payload').notNull().default(''),athleteId:text('athlete_id').notNull().references(()=>athletes.id),athleteName:text('athlete_name').notNull(),amount:integer('amount').notNull(),method:text('method').notNull(),payer:text('payer').notNull(),reference:text('reference').notNull().default(''),paidDate:text('paid_date').notNull(),status:text('status').notNull().default('confirmed'),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull(),voidReason:text('void_reason'),voidBy:text('void_by'),voidAt:text('void_at')
},t=>[uniqueIndex('payments_request_unique').on(t.requestId),index('payments_athlete_idx').on(t.athleteId)]);
export const allocations = sqliteTable('allocations',{
 id:integer('id').primaryKey({autoIncrement:true}),paymentId:integer('payment_id').notNull().references(()=>payments.id),chargeId:text('charge_id').notNull().references(()=>charges.id),amount:integer('amount').notNull()
},t=>[uniqueIndex('allocations_payment_charge_unique').on(t.paymentId,t.chargeId),index('allocations_charge_idx').on(t.chargeId)]);
export const exceptions = sqliteTable('exceptions',{
 id:text('id').primaryKey(),athleteId:text('athlete_id').notNull().references(()=>athletes.id),startDate:text('start_date').notNull(),endDate:text('end_date').notNull(),reason:text('reason').notNull(),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull(),revokedAt:text('revoked_at'),revokedBy:text('revoked_by')
},t=>[index('exceptions_athlete_idx').on(t.athleteId)]);
